### ISSUE TITLE
本项目目的是获取三维bbox？

### ISSUE THREAD

**Issue by jeannotes** [mandrenday/Construct-3D-bounding-box#1]
你好，看了代码，本项目目的是获取三维bbox吗？似乎还用到三维轮廓图

**Comment by mandrenday** [comment]
应该不叫三维轮廓图，就是车辆的外轮廓，这个代码是复现这篇论文的《BoxCars: Improving Fine-Grained Recognition of Vehicles Using 3-D Bounding Boxes in Traffic Surveillance》，具体原理可以查看论文。简单说来就是使用神经网络预测车辆的三个方向，以及检测车辆的轮廓，然后再根据论文里面的步骤逐步得到车辆的7个点，从而构造3D bbox。

**Comment by mandrenday** [comment]
> 你好，看了代码，本项目目的是获取三维bbox吗？似乎还用到三维轮廓图

应该不叫三维轮廓图，就是车辆的外轮廓，这个代码是复现这篇论文的《BoxCars: Improving Fine-Grained Recognition of Vehicles Using 3-D Bounding Boxes in Traffic Surveillance》，具体原理可以查看论文。简单说来就是使用神经网络预测车辆的三个方向，以及检测车辆的轮廓，然后再根据论文里面的步骤逐步得到车辆的7个点，从而构造3D bbox。

**Comment by mandrenday** [comment]
应该不叫三维轮廓图，就是车辆的外轮廓，这个代码是复现这篇论文的《BoxCars: Improving Fine-Grained Recognition of Vehicles Using 3-D Bounding Boxes in Traffic Surveillance》，具体原理可以查看论文。简单说来就是使用网络预测车辆的三个方向，以及检测车辆的轮廓，然后再根据论文里面的步骤逐步得到车辆的7个点，从而构造3D bbox。

**Comment by jeannotes** [comment]
@mandrenday 给个联系方式呗，一起讨论下。我最近也在做这一块

**Comment by mandrenday** [comment]
邮箱：qiumk@mail2.sysu.edu.cn，qq：1432874755
